spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3305/wxj_test
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext